### ISSUE TITLE
센서 검색시 결과창 중복 출력

### ISSUE THREAD

**Issue by xtra72** [futuretekinc/ftm_manager#1]
아래와 같이 검색을 여러번 누룰 경우, 결과창이 중복해서 나옴.
![image](https://cloud.githubusercontent.com/assets/7665315/14242890/50a3bfc8-fa8d-11e5-8cde-3e58d1d117c4.png)

**Comment by kindmonkey** [comment]
텍스트필드 미입력시 예외처리, 검색 실패시 예외 처리 추가하여 수정하였습니다.
