### ISSUE TITLE
센서노드 등록 및 삭제, 대시보드에 관한 이슈.

### ISSUE THREAD

**Issue by SEUNGYEOP-KANG** [futuretekinc/ftm_manager#6]
게이트웨이에 센서노드를 2개를 연결한 상태에서 발생한 문제에 대해 말씀 드립니다.
1. 센서 노드 2개를 연결한 후, 센서 검색 및 센서 등록은 정상적으로 진행되며, 대쉬보드에도 정상적으로 표시가 됩니다.
   ![1](https://cloud.githubusercontent.com/assets/12759120/17238996/902492da-559b-11e6-97db-d74d0f4cbd9b.JPG)
   ![2](https://cloud.githubusercontent.com/assets/12759120/17238998/9458fb7a-559b-11e6-9434-779336610926.JPG)
   ![3](https://cloud.githubusercontent.com/assets/12759120/17239001/97e6bdb8-559b-11e6-9e70-1dd0aa2e24df.JPG)
2. 등록된 센서노드 2개를 리스트에서 모두 삭제한 후, 재부팅을 진행하고 웹페이지를 로그인하면 대시보드에  undefined라는 센서노드 2개가 남아 있습니다. 이 센서노드가 리스트에 남아 있어서, 센서노드를 재등록하기 위해 센서노드 검색을 하면 검색이 되지 않습니다.
   ![7](https://cloud.githubusercontent.com/assets/12759120/17239039/f80648bc-559b-11e6-8739-4d25c0427702.JPG)
3. 등록된 센서노드 2개 중 리스트에서 하나만 삭제한 후, 재부팅을 진행하면 웹페이지 로그인 시 등록되어 있는 센서노드는 정상표시가 되어 있지만, 삭제되었던 센서노드 자리에는  undefined로 정의된 센서노드가 남아 있습니다. 이 또한 리스트에 남아 있을 시, 센서노드 검색을 진행하면 검색이 되지 않습니다.
   ![11](https://cloud.githubusercontent.com/assets/12759120/17239107/76eb05c8-559c-11e6-86f1-f66329d687ce.JPG)
4.  undefined 로 정의된 센서노드를 리스트에서 삭제를 하기 위해 설정 버튼을 클릭해도 팝업이 뜨지 않습니다. 삭제를 하려면 센서 하나하나 개별로 삭제하여 센서 모두를 삭제하면 센서노드가 사라집니다. undefined 센서노드가 삭제되면, 센서노드 검색에서 게이트웨이에 연결되어 있는 센서노드가 검색이 됩니다.
   ![8](https://cloud.githubusercontent.com/assets/12759120/17239141/bd7bacfe-559c-11e6-8bd5-ef5d6fe9f8ec.JPG)
5. undefined로 정의된 센서노드를 모두 삭제 후, 센서노드를 검색 및 등록을 하지 않고 재부팅을 진행한 후에도 대시보드에 undefined로 정의된 센서노드가 남아 있습니다.

**Comment by xtra72** [comment]
FTOM  내부에서 처리 오류로 DB에 있는 End Point를 삭제하지 않아 발생.
